# 这个文件启动： docker-compose -f docker-compose.db.yml -p whattoeat-local up -d

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # username: root, password: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
      # username: ming, password: 123
      MYSQL_USER: ming
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: testdb
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql # 必须挂载到 /var/lib/mysql 才能保证数据不丢失

  redis:
    image: redis:7-alpine
    container_name: redis-eat
    restart: always
    command: redis-server --appendonly yes # 增加这行命令开启 Redis 的持久化（AOF模式）
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data # 为 Redis 也增加一个数据持久化卷

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '8001:5540'
    depends_on:
      - redis

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  mysql_data:
  redis_data: # 定义新的 redis 卷
