# 这个文件在 npm run prod 命令下用到
# 只放与 config.yml 的差异项

db:
  mysql:
    host: database-2.cn40g8yicfus.us-east-2.rds.amazonaws.com
    name: eatdbprod
    port: 3310
    # sync: true
redis:
  host: redis
  port: 6379
google:
  callbackUrl: https://mealdice.com/api/v1/auth/google/callback
  frontendUrl: https://mealdice.com
