# 这个文件在 npm run dev 命令下用到
# 只放与 config.yml 的差异项
db:
  mysql:
    host: 127.0.0.1
    name: testdb
    port: 3307 # 这里的port要和 docker-compose.yml里映射的我电脑port一致
google:
  callbackUrl: http://localhost:3001/api/v1/auth/google/callback
  frontendUrl: http://localhost:3000
